exec-once = waybar & hyprpaper & hypridle
exec-once = systemctl --user start hyprpolkitagent
exec-once = otd-daemon
exec-once = systemctl start cups.service
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
